### ISSUE TITLE
Unsolicited feedback!

### ISSUE THREAD

**Issue by Gyromitre** [teslor/ray#11]
Hello there,

Just wanted to thank @teslor for this software, I'm using it for my 300 words-a-day challenge and it's very good. I like the customization & portability brought by HTML files.
I do have some feedback, things that I think could be improved:

- At the moment, it is not possible to setup a paragraph indentation. You can indent the whole paragraph but not just the first sentence of it. I just add a CSS rule to make it work once I finalize my chapter, using this simple instruction
```css
p { text-indent: 1em }
```

- Speaking of, I think it'd be a nice idea to add an "advanced" option where you can setup CSS instructions. I'm thinking just a textarea that would be added in a <style> tag at the beginning of the document, and would be saved along the file. Right now, for the indentation I talked about above, I need to do it manually after any save of the file. That would probably allow a lot more flexibility with the app.

- Similarly, I do not understand why there is such a limitation on font-family. Maybe a custom input[type=text] for advanced users, if they know the name of the font they want? 

- I think some improvements on visibility would be nice when it comes to searching (ctrl+f). I understand the limitation of not being able to edit the document while you are searching it, but it is not very well communicated to the user... and quite honestly the first time it happened to me I thought Ray had crashed.

- It would be a nice addition to be able to drag&drop a .HTML file into Ray. I'm not sure how much trouble that would be but I was surprized that it wasn't a native feature of Electron. It seems that you can't use "open with" also, which is a bummer. If you're wary that ppl would open HTML files that are not ray-compatible, maybe you could add a meta tag to identify Ray documents.

That's all for the moment!
I hope you keep updating this project, I think it has a lot of potential.

**Comment by teslor** [comment]
Hi Gyromitre,

I'm happy you like the app :) 300 words-a-day challenge - very interesting!

- Yes, there is no setting to set a paragraph indentation (and many others too). It's a great idea, I also had thoughts about something like this - to add ability to set some custom styles using any CSS embedded in the docs. I think it will be the high priority for next releases.

- I agree that font choice is limited at this moment (however I believe that currently included fonts are ones of the best for computer screens and reading). I have some ideas about this too (including ability to use Google Fonts). So the app fonts will be definitely improved in the future. And searching inside a document too.

- I think it's possible to implement drag&drop of html files, but yes not so easy/quickly. I will think about that :)

Thank you for this feedback, your ideas and interest to the app. I'm using Ray by myself so the app will continue to become better!
