### ISSUE TITLE
Command + S: Save dialog opens and then immediately saves.  User is unable to rename file or change location.

### ISSUE THREAD

**Issue by tylwright** [teslor/ray#4]
**Environment:** macOS 10.12.6 (Sierra) and macOS 10.13.3 (High Sierra)
**Version:** v0.2.0, v0.2.1, v0.2.2

**Repro Steps:**
1. Create a new file
2. Press Command + S (or Apple + S)

**Outcome:**
Save dialog appears for only a moment and then automatically submits itself

**Expected Outcome:**
Save dialog should appear and wait for user to click "Save" or press "Enter" before saving

**Comment by teslor** [comment]
Thanks for reporting.
The app currently has no macOS build (and is not tested there) so some issues are possible.
I will check this when create build for macOS. Versions v0.2.1, v0.2.2 don't exist yet, use the latest available version (https://github.com/teslor/ray/releases) for reference.

**Comment by tylwright** [comment]
Hi @teslor - I was opening this thinking I could assign it to myself but I unfortunately am unable to.

**Comment by teslor** [comment]
Hi! I appericate that you want to help. I assigned it to you, however I will be able to merge macOS-related updates only when I check them on macOS by myself.

**Comment by tylwright** [comment]
Pull request #5 up for review.

**Comment by tylwright** [comment]
Closing issue as this fix is now in 0.2.1!
