### ISSUE TITLE
Some vulnerabilities, Check using npm audit

### ISSUE THREAD

**Issue by ibrahimsuprapto** [teslor/ray#9]
ibrahim@zayn-falah:~/Downloads/ray-master$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install --dev electron@1.8.6  to resolve 2 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Code Execution by Re-enabling Node.js integration            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ electron                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ electron [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ electron                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/574                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ electron [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ electron > electron-download > rc > deep-extend              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

# Run  npm install --dev electron-builder@20.13.3  to resolve 3 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ electron-builder [dev]                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ electron-builder > electron-download-tf > rc > deep-extend   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ electron-builder [dev]                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ electron-builder > update-notifier > latest-version >        │
│               │ package-json > registry-auth-token > rc > deep-extend        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ electron-builder [dev]                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ electron-builder > update-notifier > latest-version >        │
│               │ package-json > registry-url > rc > deep-extend               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

# Run  npm install --dev url-loader@1.0.1  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ mime                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ url-loader [dev]                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ url-loader > mime                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/535                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

# Run  npm update rc --depth 6  to resolve 2 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ patch-package [dev]                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ patch-package > update-notifier > latest-version >           │
│               │ package-json > registry-auth-token > rc > deep-extend        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ patch-package [dev]                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ patch-package > update-notifier > latest-version >           │
│               │ package-json > registry-url > rc > deep-extend               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

# Run  npm update fill-range --depth 6  to resolve 1 vulnerability
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Cryptographically Weak PRNG                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ randomatic                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack-dev-server [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webpack-dev-server > http-proxy-middleware > micromatch >    │
│               │ braces > expand-range > fill-range > randomatic              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/157                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

[!] 9 vulnerabilities found - Packages audited: 11064 (11010 dev, 12 optional)
    Severity: 7 Low | 1 Moderate | 1 High

**Comment by teslor** [comment]
Hi, thanks for the interest and this info. I will update dependencies when create new release.
